let suggestions = [
    "futebol",
    "esportes",
    "volei",
    "handebol",
    "basquete",
    "surfe",
    "hipismo",
    "exercicios",
    "futebol feminino",
    "triathlon",
    "futebol americano",
    "golfe",
    "praticar esportes",
  ];